### ISSUE TITLE
PID issues with water subsystem

### ISSUE THREAD

**Issue by Willmish** [Willmish/comp0016-farmbeats#54]
Currently the PID control system outputs the time periods for which the pump should be on or off, and manages this by itself. 
This won't work with our asynchronous design of the system, so I suggest two solutions:

- [ ] Move the asynchronous turning on and off of the pump to the actuator itself, passing it only the time it needs to be on
- [ ] Change the control method to decide (based on the moisture of the soil, read from sensors) when to send a pump on message and when to turn it off (so time for pump to be on or off will be a multiple of clock cycles of the pid loop)

**Comment by wheatwolftianchi** [comment]
get it on it now
